"""empty message

Revision ID: 33731a35f803
Revises: 87170207d224
Create Date: 2021-11-01 16:41:21.804874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33731a35f803'
down_revision = '87170207d224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
