"""Add unique id to shows

Revision ID: 87170207d224
Revises: 756b6d587a2d
Create Date: 2021-10-15 18:04:33.586879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87170207d224'
down_revision = '756b6d587a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
