"""Add missing fields to artists table

Revision ID: b83ff006d4d6
Revises: c249978f3123
Create Date: 2021-10-15 17:12:09.193337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83ff006d4d6'
down_revision = 'c249978f3123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('looking_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'looking_venue')
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
